act: relu
add_self_loop: true
backbone: gat
balance: true
base_temperature: 0.07
batch_size: 32
bias: false
ckpt_dir: out/checkpoints/supcon_cora/2023-12-07_14-52-58
classifier_epochs: 10000
contrast_mode: all
contrast_reg: 0.5
dataset: cora
datetime: 2023-12-07_14-52-58
device: !!python/object/apply:torch.device
- cuda
dropout: 0.5
epochs: 300
fix_dataset: false
gat:
  act: elu
  attn_drop: 0.5
  feat_drop: 0.5
  num_heads: 8
  tail_act: elu
gcn:
  act: relu
  tail_act: relu
gn: false
gpu:
  id: 2
  use: true
gpu_id: 2
head: mlp
hid_dim: 64
imb_ratio: 10
lr: 0.01
lr_scheduler: true
model: supcon
monitor: acc
multirun: 1
n_layer: 2
norm_feat: false
num_cls: 7
patience: 1000
root_ckpt_dir: out/checkpoints/supcon_cora
sage:
  act: relu
  agg: mean
  feat_drop: 0.5
  tail_act: relu
temperature: 0.07
weight_decay: 0.0001
